### ISSUE TITLE
When Serving static files: "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by chrisbrake** [kennethreitz/responder#165]
Using the example code:
```import responder

api = responder.API()

@api.route("/{greeting}")
async def greet_world(req, resp, *, greeting):
    resp.text = f"{greeting}, world!"

if __name__ == '__main__':
    api.run()
```

I dropped a couple files in the `static/` directory, and while it does successfully serve the files, I get these messages back in the log whenever it loads my index.html file.
```
INFO: ('127.0.0.1', 46560) - "GET /index.html HTTP/1.1" 302
INFO: ('127.0.0.1', 46560) - "GET / HTTP/1.1" 304
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 387, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/uvicorn/middleware/message_logger.py", line 59, in __call__
    await self.inner(self.receive, self.send)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable

INFO: ('127.0.0.1', 46564) - "GET /static/chat.js HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 387, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/uvicorn/middleware/message_logger.py", line 59, in __call__
    await self.inner(self.receive, self.send)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/home/cig/PycharmProjects/PythonSandbox/venv/lib64/python3.6/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable

INFO: ('127.0.0.1', 46568) - "GET /static/chat.js HTTP/1.1" 500
```

To reproduce:
1. Check out my [sandbox](https://github.com/chrisbrake/PythonSandbox)
2. Install `responder`
3. Go into the `toDo` module
4. Run `app.py`
5. Go to http://127.0.0.1:5042/static/

**Comment by kennethreitz** [comment]
this should now be fixed

**Comment by chrisbrake** [comment]
Thanks

Can you point me to the pr that resolved it?
I fired up the debugger to try and figure it out and failed.  So I'm curious what the solution was.
