### ISSUE TITLE
Whitenoise-related 404 calls _default_wsgi_app which contains nothing

### ISSUE THREAD

**Issue by hartym** [kennethreitz/responder#185]
**How to reproduce ?**

- Create basic empty project.
```
import responder
api = responder.API()
```
- Serve it
- Go to /static/anythingthatdoesnotexist

**What happens ?**

```
500 Server Error
Traceback (most recent call last):
  File "/Users/rd/.virtualenvs/Evaluate/lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 80, in __call__
    await asgi(receive, self.send)
  File "/Users/rd/.virtualenvs/Evaluate/lib/python3.7/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/Users/rd/.virtualenvs/Evaluate/lib/python3.7/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rd/.virtualenvs/Evaluate/lib/python3.7/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/Users/rd/.virtualenvs/Evaluate/lib/python3.7/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable
```

**What is expected ?**

404, most probably ?

**Environment**

OSX Mojave, Python 3.7.1

**Comment by tomchristie** [comment]
Haven’t looked into this, it might be worth swapping out asgiref’s WSGI adapter, for Starlettes WSGI adapter.

**Comment by taoufik07** [comment]
#297
