### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'AsyncGenerator'

### ISSUE THREAD

**Issue by msterzhang** [kennethreitz/responder#187]
# 1.my code

	#   -*-coding:utf-8 -*-
	#   @Author: 'ZLOE'
	#   @Time: '2018/11/3 22:26'
	import responder

	api = responder.API()

	@api.route("/")
	def hello_world(req, resp):
		resp.text = "hello, world!"

	if __name__ == '__main__':
		api.run()

# 2.Error

	D:\python\python.exe E:/python/requests框架/respond/index.py
	Traceback (most recent call last):
	  File "E:/python/requests框架/respond/index.py", line 4, in <module>
		import responder
	  File "E:\python\requests框架\respond\responder\__init__.py", line 1, in <module>
		from .core import *
	  File "E:\python\requests框架\respond\responder\core.py", line 1, in <module>
		from .api import API
	  File "E:\python\requests框架\respond\responder\api.py", line 16, in <module>
		from starlette.exceptions import ExceptionMiddleware
	  File "D:\python\lib\site-packages\starlette\exceptions.py", line 5, in <module>
		from starlette.debug import get_debug_response
	  File "D:\python\lib\site-packages\starlette\debug.py", line 5, in <module>
		from starlette.requests import Request
	  File "D:\python\lib\site-packages\starlette\requests.py", line 8, in <module>
		from starlette.formparsers import FormParser, MultiPartParser
	  File "D:\python\lib\site-packages\starlette\formparsers.py", line 62, in <module>
		class FormParser:
	  File "D:\python\lib\site-packages\starlette\formparsers.py", line 64, in FormParser
		self, headers: Headers, stream: typing.AsyncGenerator[bytes, None]
	AttributeError: module 'typing' has no attribute 'AsyncGenerator'

	Process finished with exit code 1

**Comment by hartym** [comment]
What python version are you using?
`typing.AsyncGenerator` was introduced in python 3.5.4, and responder / starlette only support Python 3.6+, that's maybe your problem?

**Comment by msterzhang** [comment]
python3.6
![snipaste_2018-11-03_23-05-34](https://user-images.githubusercontent.com/31364579/47953790-25282100-dfbd-11e8-965f-75a6a9edc01f.jpg)

**Comment by duobei** [comment]
> python3.6
> ![snipaste_2018-11-03_23-05-34](https://user-images.githubusercontent.com/31364579/47953790-25282100-dfbd-11e8-965f-75a6a9edc01f.jpg)

我试了下，Python 3.6.0 不行，Python 3.7.1 就可以了
