### ISSUE TITLE
Is there a recommended way / example of using websockets with responder?

### ISSUE THREAD

**Issue by nickponline** [kennethreitz/responder#198]
Is there a recommended way / example of using websockets with responder?

**Comment by nickponline** [comment]
I would be happy to do the code to support this if someone could point me in the right direction

**Comment by paalbra** [comment]
Not currently. You might want to have a look in #190

**Comment by waynew** [comment]
For what it's worth, if you need some websockets you can use code like this right now:

```
import responder
from starlette.websockets import WebSocket

api = responder.API()

class PingPong:
    def __init__(self, scope):
        self.scope = scope

    async def __call__(self, receive, send):
        ws = WebSocket(self.scope, receive=receive, send=send)
        await ws.accept()
        data = await ws.receive_text()
        if data == "ping":
            await ws.send_text("pong")
        await ws.close()

api.mount("/ping", PingPong)
```

**Comment by taoufik07** [comment]
Sorry for the delay ! You can something like
```python
@api.route('/ws', websocket=True)
async def ws1(ws):
    await ws.accept()
    while True:
        name = await ws.receive_text()
        await ws.send_text(f"Hello {name}!")
    await ws.close()
```

**Comment by paalbra** [comment]
@taoufik07 That doesn't seem to work (as mentioned in #190). Or am I missing something here?

**Comment by paalbra** [comment]
No, it's not the `starlette.lifespan` error. I used starlette 0.8 (to circumvent #226) and responder 1.1.2.

```
INFO: Started server process [32]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://127.0.0.1:5042 (Press CTRL+C to quit)
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/test/responder/venv/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 140, in run_asgi
    result = await asgi(self.asgi_receive, self.asgi_send)
  File "/test/responder/venv/lib/python3.6/site-packages/responder/api.py", line 223, in asgi
    req = models.Request(scope, receive=receive, api=self)
  File "/test/responder/venv/lib/python3.6/site-packages/responder/models.py", line 97, in __init__
    self._starlette = StarletteRequest(scope, receive)
  File "/test/responder/venv/lib/python3.6/site-packages/starlette/requests.py", line 27, in __init__
    assert scope["type"] == "http"
AssertionError
```

**Comment by taoufik07** [comment]
@paalbra it's working, the error is related to "lifespan" but now it's fixed, you can wait for the new release or play with directly from the repo

**Comment by paalbra** [comment]
@taoufik07 Yeah, thanks. Looks lite it's working if I pip install from the current master branch. Looking forward to the next release :)

**Comment by paalbra** [comment]
Just tried to install responder again and got responder 1.2.0 and starlette 0.9.9. The following works fine with those versions :+1: 

```python
import responder

api = responder.API()

index_html = """<!DOCTYPE html>
<head>
<meta charset="utf-8">
<title>Responder</title>
<script>
const ws = new WebSocket('ws://localhost:5042/ws');

ws.addEventListener('message', function (event) {
    var msg = "Message from server: " + event.data;
    document.body.innerHTML = "<p>" + msg + "</p>";
    console.log(event);
});
</script>
</head>
<body>
</body>
"""

@api.route('/')
def index(req, resp):
    resp.text = index_html

@api.route('/ws', websocket=True)
async def websocket(ws):
    await ws.accept()
    await ws.send_text("Hello client!")
    await ws.close()

api.run()
```

**Comment by taoufik07** [comment]
@kennethreitz I guess we need to close this

**Comment by Serkan-devel** [comment]
But is this documented?

**Comment by taoufik07** [comment]
Yep https://python-responder.org/en/latest/tour.html#websocket-support

**Comment by tedder** [comment]
updated link since that domain has been hijacked: https://responder.readthedocs.io/en/latest/tour.html#websocket-support
