### ISSUE TITLE
"seconds" parameter not supported on on_event decorator, for "tick" event type

### ISSUE THREAD

**Issue by emacsuser123** [kennethreitz/responder#204]
Hello.

When I execute the responder server using the following code:

```
@api.on_event('tick', seconds=10)
async def do_periodic_stuff():
    print('Periodic stuff being done here ...')
```

I get the error:

> Traceback (most recent call last):
>   File "./api_server.py", line 267, in <module>
>     @api.on_event('tick', seconds=10)
>   File "/home/bob/.local/share/virtualenvs/hpms-okBXuRxW/lib/python3.7/site-packages/responder/api.py", line 488, in decorator
>     self.add_event_handler(event_type, func, **args)
> TypeError: add_event_handler() got an unexpected keyword argument 'seconds'
> 

Thanks.
-Bob V

**Comment by emacsuser123** [comment]
Yeah, that's what I saw. The only thing is that the API documentation states it is supported.
Anyway, just wanted to confirm that it is known it is not supported yet and it will be addressed in the future. Thanks.
