### ISSUE TITLE
Internal server error on docs_route:  'APISpec' object has no attribute 'add_path'

### ISSUE THREAD

**Issue by mmanhertz** [kennethreitz/responder#212]
The newest version of apispec (==1.0.0b5), removed the `add_` prefix from some methods on `APISpec`, breaking the schema generation. (see [this commit](https://github.com/marshmallow-code/apispec/commit/09c32943ca08cee18b991faf50a9f1a13cb6a25b#diff-f8882f275ab781d2aacc6a44f0171eaf))

This means I get an internal server error, when I try to access the docs_route:

```
INFO: ('127.0.0.1', 52287) - "GET /docs HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "...\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await asgi(self.receive, self.send)
  File "...\lib\site-packages\starlette\exceptions.py", line 69, in app
    raise exc from None
  File "...\lib\site-packages\starlette\exceptions.py", line 61, in app
    await instance(receive, sender)
  File "...\lib\site-packages\starlette\middleware\gzip.py", line 34, in __call__
    await self.inner(receive, self.send_with_gzip)
  File "...\lib\site-packages\responder\api.py", line 227, in asgi
    req, scope=scope, send=send, receive=receive
  File "...\lib\site-packages\responder\api.py", line 306, in _dispatch_request
    await self._execute_route(route=route, req=req, resp=resp, **options)
  File "...\lib\site-packages\responder\api.py", line 329, in _execute_route
    await r
  File "...\lib\site-packages\responder\background.py", line 45, in __call__
    return await loop.run_in_executor(None, fn)
  File "C:\Python37\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "...\lib\site-packages\responder\api.py", line 435, in docs_response
    resp.text = self.docs
  File "...\lib\site-packages\responder\api.py", line 563, in docs
    document.content = yaml.safe_load(self.openapi)
  File "...\lib\site-packages\responder\api.py", line 195, in openapi
    return self._apispec.to_yaml()
  File "...\lib\site-packages\responder\api.py", line 186, in _apispec
    spec.add_path(path=route, operations=operations)
AttributeError: 'APISpec' object has no attribute 'add_path'
```

**Comment by mmanhertz** [comment]
I opened a PR that I believe fixes the problem.

**Comment by PruthviKumarBK** [comment]
Im on version 1.1.0 of APISpec and get this same error. 
```

**Comment by PruthviKumarBK** [comment]
[2019-03-29 19:27:37 +1100] [33025] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/bkp2/projects/personal/PROTON/main.py", line 85, in <module>
    spec.add_path(resource= rc_Ictrl_get_schema_information)
AttributeError: 'APISpec' object has no attribute 'add_path'
```
