### ISSUE TITLE
Error 500 on static files larger than 1Mb 

### ISSUE THREAD

**Issue by michela** [kennethreitz/responder#248]
Using responder static file routing, I can only serve files <1Mb. Is this configurable somewhere or a bug?
 
I can't repro this with underlying packages - I can serve the same file via starlette and uvicorn directly using the example routing
https://www.starlette.io/staticfiles/

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/var/www/.local/share/virtualenvs/acl-server-QKRCedeE/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 387, in run_asgi
    result = await asgi(self.receive, self.send)
  File "/var/www/.local/share/virtualenvs/acl-server-QKRCedeE/lib/python3.7/site-packages/uvicorn/middleware/message_logger.py", line 59, in __call__
    await self.inner(self.receive, self.send)
  File "/var/www/.local/share/virtualenvs/acl-server-QKRCedeE/lib/python3.7/site-packages/asgiref/wsgi.py", line 41, in __call__
    await self.run_wsgi_app(message)
  File "/var/www/.local/share/virtualenvs/acl-server-QKRCedeE/lib/python3.7/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/var/www/miniconda3/lib/python3.7/asyncio/tasks.py", line 384, in wait_for
    return await fut
  File "/var/www/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/www/.local/share/virtualenvs/acl-server-QKRCedeE/lib/python3.7/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/var/www/.local/share/virtualenvs/acl-server-QKRCedeE/lib/python3.7/site-packages/asgiref/wsgi.py", line 118, in run_wsgi_app
    for output in self.wsgi_application(environ, self.start_response):
TypeError: 'NoneType' object is not iterable

INFO: ('10.20.15.1', 53031) - "GET /img/large.jpg HTTP/1.0" 500
```

**Comment by michela** [comment]
Issue was needing to restart server. Files added since app started are not found
