### ISSUE TITLE
ModuleNotFoundError on import with latest version of starlette (0.11.1)

### ISSUE THREAD

**Issue by bpeake-illuscio** [kennethreitz/responder#299]
Traceback:

```
Traceback (most recent call last):
    ....
  File "/Users/williampeake/venvs/ingester-py-37/lib/python3.7/site-packages/spanreed/_api.py", line 1, in <module>
    import responder
  File "/Users/williampeake/venvs/ingester-py-37/lib/python3.7/site-packages/responder/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/williampeake/venvs/ingester-py-37/lib/python3.7/site-packages/responder/core.py", line 1, in <module>
    from .api import API
  File "/Users/williampeake/venvs/ingester-py-37/lib/python3.7/site-packages/responder/api.py", line 20, in <module>
    from starlette.middleware.lifespan import LifespanMiddleware
ModuleNotFoundError: No module named 'starlette.middleware.lifespan'
```

Pinning starlette to version `0.10.3` in my setup.cfg fixes this issue, but version `0.11.1` throws the above error.

**Comment by taoufik07** [comment]
@tomchristie is restructuring starlette

**Comment by tomchristie** [comment]
Responder is pinned to 0.10.x, no?

It’s a trivial PR which i’ll make for 0.11, but you shouldn’t be seeing this in the first place?

**Comment by taoufik07** [comment]
it's not released yet + 0.10.6 is not working "LifespanHandler not found in routing.py"

**Comment by tomchristie** [comment]
See https://github.com/kennethreitz/responder/issues/300#issuecomment-465610991

**Comment by taoufik07** [comment]
New release **v1.3.0** :tada:
