### ISSUE TITLE
api.requests does not trigger startup events

### ISSUE THREAD

**Issue by bpeake-illuscio** [kennethreitz/responder#324]
Version 1.3.0 installed through pip. Startup events appear to be triggering properly when actually running the service, but do not get triggered when accessing through `api.requests` in unit tests.

Example Code:

```
import responder


TEST_DICT = dict()
api = responder.API()


@api.on_event("startup")
def set_dict_values():
    TEST_DICT["test"] = "value"


@api.route("/test")
def test_route(req: responder.Request, resp: responder.Response):
    assert TEST_DICT["test"] == "value"


if __name__ == '__main__':
    api.requests.get("/test")

```

Output:

```
Traceback (most recent call last):
  File "/Users/user/Documents/Source_Code/services/hippo-py/zdevelop/scratch/scratch1.py", line 19, in <module>
    api.requests.get("/test")
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/starlette/testclient.py", line 382, in request
    json=json,
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/starlette/testclient.py", line 211, in send
    raise exc from None
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/starlette/testclient.py", line 208, in send
    loop.run_until_complete(connection(receive, send))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/starlette/middleware/errors.py", line 125, in asgi
    raise exc from None
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/starlette/middleware/errors.py", line 103, in asgi
    await asgi(receive, _send)
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 33, in __call__
    await self.inner(receive, self.send_with_gzip)
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/responder/api.py", line 264, in asgi
    req, scope=scope, send=send, receive=receive
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/responder/api.py", line 353, in _dispatch_request
    await self._execute_route(route=route, req=req, resp=resp, **options)
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/responder/api.py", line 376, in _execute_route
    await r
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/responder/background.py", line 44, in __call__
    return await run_in_threadpool(func, *args, **kwargs)
  File "/Users/user/venvs/ingester-py-37/lib/python3.7/site-packages/starlette/concurrency.py", line 24, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/user/Documents/Source_Code/services/hippo-py/zdevelop/scratch/scratch1.py", line 15, in test_route
    assert TEST_DICT["test"] == "value"
KeyError: 'test'
```

**Comment by taoufik07** [comment]
Use context managers :

```python
with api.requests as client:
   client.get("/test")
   
```
`TestClient` " "mimics" a server " to handle lifespan.

**Comment by bpeake-illuscio** [comment]
Thank you! Will test this out

**Comment by bpeake-illuscio** [comment]
Confirmed that this solved the problem. Thank you for your help! It might be useful to add to the docs, I did a scan and don't see an example of this in the feature tour.

https://python-responder.org/en/latest/tour.html#using-requests-test-client
