### ISSUE TITLE
@kenneth-reitz  @mmanhertz

### ISSUE THREAD

**Issue by PruthviKumarBK** [kennethreitz/responder#340]
@kenneth-reitz  @mmanhertz 

I'm using APISpec version 1.1.0 and still receive the same error as above. Appreciate your help.

```
[2019-03-29 19:27:37 +1100] [33025] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/anaconda3/envs/proton_py3/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/bkp2/projects/personal/PROTON/main.py", line 85, in <module>
    spec.add_path(resource= rc_Ictrl_get_schema_information)
AttributeError: 'APISpec' object has no attribute 'add_path'
```

_Originally posted by @PruthviKumarBK in https://github.com/kennethreitz/responder/issues/212#issuecomment-477912196_

**Comment by kobayashi** [comment]
Does your main.py has `spec.add_path` at line 85? As @mmanhertz mentioned, APISpec removed `app_` . You cannot use `add_path` method in your version. This might not related to responder.

**Comment by kobayashi** [comment]
Close this issue
