### ISSUE TITLE
can not add workers in API.run

### ISSUE THREAD

**Issue by ixuuux** [kennethreitz/responder#341]
hi,
- My run:
```python
api = responder.API()
......
api.run(address='192.168.1.56', port=1005, workers=2)
```
- Get error
```python
Traceback (most recent call last):
  File "E:/WorkDir/WorkDir/Taobao/ParseTklByResponder/app/parseTKL.py", line 174, in <module>
    main()
  File "E:/WorkDir/WorkDir/Taobao/ParseTklByResponder/app/parseTKL.py", line 169, in main
    api.run(address='192.168.1.56', port=1005, workers=2)
  File "C:\Users\admin\.virtualenvs\ParseTklByResponder-fJ87HmF5\lib\site-packages\responder\api.py", line 687, in run
    self.serve(**kwargs)
  File "C:\Users\admin\.virtualenvs\ParseTklByResponder-fJ87HmF5\lib\site-packages\responder\api.py", line 682, in serve
    spawn()
  File "C:\Users\admin\.virtualenvs\ParseTklByResponder-fJ87HmF5\lib\site-packages\responder\api.py", line 680, in spawn
    uvicorn.run(self, host=address, port=port, debug=debug, **options)
  File "C:\Users\admin\.virtualenvs\ParseTklByResponder-fJ87HmF5\lib\site-packages\uvicorn\main.py", line 274, in run
    supervisor.run(server.run, sockets=[socket])
  File "C:\Users\admin\.virtualenvs\ParseTklByResponder-fJ87HmF5\lib\site-packages\uvicorn\supervisors\multiprocess.py", line 33, in run
    process.start()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
```

python 3.6.5
windows 7
responder 1.3.0

I am not sure if API.run supports adding workers. 
what should I do?
Thanks a lot !

**Comment by tomchristie** [comment]
Don't think that'll work on windows, due to differences in how it handles multiprocessing. (Ends up attempting to pickle the `app` instance, which may or may not succeed.)
You'd need to run `uvicorn` directly to get the multiple workers.

**Comment by ixuuux** [comment]
> Don't think that'll work on windows, due to differences in how it handles multiprocessing. (Ends up attempting to pickle the `app` instance, which may or may not succeed.)
> You'd need to run `uvicorn` directly to get the multiple workers.

Ok, thank you very much for your answer. I think I need to test on Linux or MAC. please forgive me for being a newbie, anyway, I will try my best, and Thank you again for your reply.
